basePath: /
definitions:
  godoc.MessageResponse:
    properties:
      message:
        type: string
    type: object
  godoc.MessagesResponse:
    properties:
      message:
        items:
          type: string
        type: array
    type: object
  request.ChangePasswordUserRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  request.ForgotPasswordUserRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.LoginUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.RegisterUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.ResetPasswordUserRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      reset_token:
        type: string
    required:
    - new_password
    - reset_token
    type: object
  request.VerifyOtpResetPasswordUserRequest:
    properties:
      email:
        type: string
      otp_code:
        type: string
    required:
    - email
    - otp_code
    type: object
  response.ChanagePasswordUserResponse:
    properties:
      message:
        type: string
    type: object
  response.ForgotPasswordUserResponse:
    properties:
      message:
        type: string
    type: object
  response.LoginUserResponse:
    properties:
      access_token:
        type: string
    type: object
  response.ProfileUserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  response.RegisterUserResponse:
    properties:
      message:
        type: string
    type: object
  response.ResetPasswordUserResponse:
    properties:
      message:
        type: string
    type: object
  response.VerifyOtpResetPasswordUserRepsonse:
    properties:
      reset_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: description
  title: Title
  version: "1.0"
paths:
  /user/change-password:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ChangePasswordUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ChanagePasswordUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      security:
      - BearerAuth: []
      - OAuth2Password: []
      summary: Đổi mật khẩu
      tags:
      - User
  /user/forgot-password:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ForgotPasswordUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ForgotPasswordUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      summary: Quên mật khẩu
      tags:
      - User
  /user/login:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      summary: Đăng nhập
      tags:
      - User
  /user/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProfileUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      security:
      - BearerAuth: []
      - OAuth2Password: []
      summary: Thông tin người dùng
      tags:
      - User
  /user/register:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.RegisterUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      summary: Đăng ký
      tags:
      - User
  /user/reset-password:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ResetPasswordUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResetPasswordUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      summary: Đặt lại mật khẩu
      tags:
      - User
  /user/verify-otp-reset-password:
    post:
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.VerifyOtpResetPasswordUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.VerifyOtpResetPasswordUserRepsonse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/godoc.MessagesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/godoc.MessageResponse'
      summary: Xác thực OTP đặt lại mật khẩu
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
  OAuth2Password:
    flow: password
    scopes:
      read: Grants read access
      write: Grants write access
    tokenUrl: http://localhost:8080/user/login
    type: oauth2
swagger: "2.0"
